server:
  port: 80
  servlet:
    context-path: /site
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomdb
    username: ecomuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: INSERT-YOUR-OWN
            client-secret: INSERT-YOUR-OWN
            scope:
              - email
              - profile
          facebook:
            client-id: INSERT-YOUR-OWN
            client-secret: INSERT-YOUR-OWN
            scope:
              - email
              - public_profile

